### ISSUE TITLE
[Bug]: GraphQL errors on initial connection

### ISSUE THREAD

**Issue by husq-nz** [ruaan-deysel/ha-unraid#125]
### 🐛 Bug Description

Unable to connect to GraphQL during initial setup.

### 🔄 Steps to Reproduce

1. Add add-on
2. Add Integration
3. Use server IP and API key (API key with either _viewer_ or _admin_ both fail the same)
4. Receive this error: ```Unexpected error: GraphQL query failed: Failed to retrieve VM domains: VMs are not available (path: ['vms', 'domains']); Failed to get UPS data: No UPS data returned from apcaccess (path: ['upsDevices'])```

### ✅ Expected Behavior

Connection is created and integration populates correctly.

### 📂 Bug Category

Setup/Configuration - Config flow, API connection

### 🖥️ Unraid Version

7.2.3

### 📦 Integration Version

2025.12.1

### 🏠 Home Assistant Version

2025.12.4

### 🏗️ Home Assistant Installation Type

Home Assistant OS (HAOS)

### 📋 Relevant Logs

```shell
This error originated from a custom integration.

Logger: custom_components.unraid.coordinator
Source: custom_components/unraid/coordinator.py:142
integration: Unraid (documentation, issues)
First occurred: 6:16:34 PM (23 occurrences)
Last logged: 6:28:52 PM

System data update failed: Unexpected error: GraphQL query failed: Failed to retrieve VM domains: VMs are not available (path: ['vms', 'domains']); Failed to get UPS data: No UPS data returned from apcaccess (path: ['upsDevices'])
System data update failed: Unexpected error: GraphQL query failed: Failed to get UPS data: No UPS data returned from apcaccess (path: ['upsDevices'])
Traceback (most recent call last):
  File "/config/custom_components/unraid/coordinator.py", line 142, in _async_update_data
    raw_data = await self.api_client.query(query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/api.py", line 267, in query
    raise Exception(f"GraphQL query failed: {'; '.join(error_messages)}")
Exception: GraphQL query failed: Failed to retrieve VM domains: VMs are not available (path: ['vms', 'domains']); Failed to get UPS data: No UPS data returned from apcaccess (path: ['upsDevices'])
```

### 🌐 Network Setup

```markdown
Both devices are on the same subnet. There are no firewalls preventing connectivity.
```

### 📝 Additional Context

```markdown

```

### ✅ Checklist

- [x] I have searched existing [open](https://github.com/ruaan-deysel/ha-unraid/issues) and [closed](https://github.com/ruaan-deysel/ha-unraid/issues?q=is%3Aissue+is%3Aclosed) issues to ensure this isn't a duplicate
- [x] I am running Unraid 7.2.0 or later (required for GraphQL API)
- [x] I have reproduced the issue on the latest version to confirm it still exists
- [x] I have tried restarting Home Assistant
- [x] I have tried reloading the Unraid integration
- [x] I have enabled debug logging and included relevant logs

**Comment by ruaan-deysel** [comment]
Do you have UPS connected  / VMs running on your server or not?

Looks like you don't but just making sure

**Comment by husq-nz** [comment]
Yep - I have a VM running. 

My UPS is using NUT and not the builtin apcupsd (I can switch over to that if that would help with troubleshooting - but it's currently disabled in the UI).

**Comment by ruaan-deysel** [comment]
> Yep - I have a VM running.
> 
> My UPS is using NUT and not the builtin apcupsd (I can switch over to that if that would help with troubleshooting - but it's currently disabled in the UI).

Mmmm... I need to check if Unraid's API supports NUT. I'm using the builtin apcupsd which it supports. 

I tested with a VM with spaces in the name. How's your VMs named? With or without spaces, Numbers, dashes, etc?

**Comment by husq-nz** [comment]
Hyphens, no spaces. I'll switch over to apcupsd and see if that helps at least the UPS part...

**Comment by ruaan-deysel** [comment]
> Hyphens, no spaces. I'll switch over to apcupsd and see if that helps at least the UPS part...

I'll have a look how it handles VMs with special characters

**Comment by ruaan-deysel** [comment]
> Hyphens, no spaces. I'll switch over to apcupsd and see if that helps at least the UPS part...

I checked and Unraid API doesn't support NUT yet and just the APCUPSD for now.

**Comment by robertjoramo** [comment]
I get the same error. I don't have UPS or VMs setup at all.

**Comment by davidvidmar** [comment]
I get same error on initialization: 
_Failed setup, will retry: Unexpected error: GraphQL query failed: Failed to get UPS data: No UPS data returned from apcaccess (path: ['upsDevices'])_

I have one VM (named "Windows Server 2025") and no UPS. Feel free to reach out for some logs.

**Comment by EagleeyeKai** [comment]
> I get the same error. I don't have UPS or VMs setup at all.

Same here..

**Comment by Milancarends** [comment]
I have the same error code. After changing: Start APC UPS daemon: to YES. Everything works...

**Comment by EagleeyeKai** [comment]
> I have the same error code. After changing: Start APC UPS daemon: to YES. Everything works...

This resolved the UPS Error, but I still got the VM Warning. I do not run VMs and the option has been deactivated in Unraid. I turned it on, but this did not help.

`Unexpected error: GraphQL query failed: Failed to retrieve VM domains: VMs are not available (path: ['vms', 'domains'])`

**Comment by robertjoramo** [comment]
Same result as EagleeeyeKai reports. USP error can be resolved by setting Start UPS deamon to YES (although not sure that is a good solution?). Enabling VM option in Unraid did not fix VM error. (did not try to run a VM).

**Comment by ruaan-deysel** [comment]
Should be fixed now. You can test it in the devcontainer before I release new version.
Just fork this repo and open in vs code. Make sure you have docker installed and vs code docker extension. It will ask you to re-open in container and then in container run ./scripts/develop to start the HA instance that you can access from http://localhost:8123. No need to have HACS installed just add the Integration and see if it works.

Other option is to copy the unraid source code files to your HA instance.

**Comment by ruaan-deysel** [comment]
Fixed and released in v2025.12.2. Release: https://github.com/ruaan-deysel/ha-unraid/releases/tag/v2025.12.2

**Comment by husq-nz** [comment]
Hey @ruaan-deysel - looks like the VM stuff is still not quite working in 2025.12.2.

I've tried a 'clean install' - removing 2025.12.1 entirely and reinstalling 2025.12.2. Rebooted twice after install. Based on the debug logs, it _looks_ like the API connects but is failing on my VMs.

I have 3 VMs - each of them is named: serveros-application (i.e. linux-tdarr). No spaces or special characters.

API role is set to ADMIN (and for good measure I've manually added full perms as well).

```2025-12-31 17:23:57.320 DEBUG (MainThread) [custom_components.unraid.api] Checking for redirect at http://192.168.1.254/graphql
2025-12-31 17:23:57.322 DEBUG (MainThread) [custom_components.unraid.api] HTTP response status: 302
2025-12-31 17:23:57.322 DEBUG (MainThread) [custom_components.unraid.api] Redirect location: https://192-168-1-254.[redacted].myunraid.net/graphql
2025-12-31 17:23:57.322 INFO (MainThread) [custom_components.unraid.api] Discovered myunraid.net redirect (Strict mode): https://192-168-1-254.[redacted].myunraid.net/graphql
2025-12-31 17:23:57.322 DEBUG (MainThread) [custom_components.unraid.api] Using URL: https://192-168-1-254.[redacted].myunraid.net/graphql
2025-12-31 17:23:57.570 DEBUG (MainThread) [custom_components.unraid.coordinator] Starting system data update
2025-12-31 17:23:58.015 DEBUG (MainThread) [custom_components.unraid.api] Full GraphQL error response: [{'message': 'Failed to retrieve VM domains: VMs are not available', 'locations': [{'line': 3, 'column': 27}], 'path': ['vms', 'domains'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]
2025-12-31 17:23:58.015 INFO (MainThread) [custom_components.unraid.api] Some optional features unavailable: Failed to retrieve VM domains: VMs are not available (path: ['vms', 'domains'])
2025-12-31 17:23:58.027 DEBUG (MainThread) [custom_components.unraid.coordinator] System data update completed successfully
2025-12-31 17:23:58.027 ERROR (MainThread) [custom_components.unraid.coordinator] System data update failed: Unexpected error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/config/custom_components/unraid/coordinator.py", line 212, in _async_update_data
    return self._parse_system_data(raw_data)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/config/custom_components/unraid/coordinator.py", line 264, in _parse_system_data
    for vm_data in vms_data.get("domains", []):
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-12-31 17:23:58.028 DEBUG (MainThread) [custom_components.unraid.coordinator] Finished fetching babel System data in 0.458 seconds (success: False)
```

**Comment by ruaan-deysel** [comment]
Ok. I think I found the bug. I tested it now on 4 VMS

Unraid VMs.
<img width="637" height="231" alt="Image" src="https://github.com/user-attachments/assets/159d3702-a2ec-42fa-9d80-5ef4646ccd96" />

HA Unraid VMs

<img width="539" height="206" alt="Image" src="https://github.com/user-attachments/assets/b2e5808d-6697-4e67-9565-f900968ef680" />

Can you copy the source code from the [https://github.com/ruaan-deysel/ha-unraid/tree/feature/custom-ports](url) branch and overwrite the code in your HA instance. Restart HA and see if it works for you. You might need to re-add the integration as there's other updates in the branch too.

**Comment by husq-nz** [comment]
Yep, that seems to have solved it!

**Comment by ABEIDO** [comment]
Would be nice to have options like below in integration during initial setup regarding UPS:

UPS Monitoring:
- APC UPS
- NUT UPS (if/when api support will come)
- Disabled

As a NUT users shouldnt enable APC UPS Daemon as it might cause unexpected UPS behaviour and system instabilities..
Im guessing the APC UPS error is only cosmetical at the moment or does it effect anything?

**Comment by ruaan-deysel** [comment]
> Would be nice to have options like below in integration during initial setup regarding UPS:
> 
> UPS Monitoring:
> - APC UPS
> - NUT UPS (if/when api support will come)
> - Disabled
> 
> As a NUT users shouldnt enable APC UPS Daemon as it might cause unexpected UPS behaviour and system instabilities..
> Im guessing the APC UPS error is only cosmetical at the moment or does it effect anything?

You can leave APC service disabled. The integration won't create APC UPS entities. Debug logs will still show UPS not detected as it's coming from GraphQL. Just cosmetic. 

I'll check if I can suppress it.

**Comment by ABEIDO** [comment]
Nice would be good as graphapi logs on Unraid gets kinda spammed by this.

**Comment by ruaan-deysel** [comment]
> Nice would be good as graphapi logs on Unraid gets kinda spammed by this.

Do you see these in the graphql-api.log when disabling the built-in unraid ups service?

`[23:01:55 ERROR UPSService]: Error getting UPS data: {"apiVersion":"4.29.2+c39b0b26","logger":"UPSService","context":"UPSService"}
[23:01:55 ERROR ExceptionsHandler]: Failed to get UPS data: No UPS data returned from apcaccess {"apiVersion":"4.29.2+c39b0b26","logger":"ExceptionsHandler","context":"ExceptionsHandler"}
    err: {
      "type": "Error",
      "message": "Failed to get UPS data: No UPS data returned from apcaccess",
      "stack":
          Error: Failed to get UPS data: No UPS data returned from apcaccess
              at UPSService.getUPSData (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21359:19)
              at async UPSResolver.upsDevices (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21652:25)`

**Comment by ABEIDO** [comment]
I cant really disable it i think, i can only stop it or am i missing something?

Otherwise below log keeps repeating (log is filled with it):

```
[23:01:24 ERROR UPSService]: Error getting UPS data: {"apiVersion":"4.29.2+c39b0b26","logger":"UPSService","context":"UPSService"}
[23:01:24 ERROR ExceptionsHandler]: Failed to get UPS data: No UPS data returned from apcaccess {"apiVersion":"4.29.2+c39b0b26","logger":"ExceptionsHandler","context":"ExceptionsHandler"}
    err: {
      "type": "Error",
      "message": "Failed to get UPS data: No UPS data returned from apcaccess",
      "stack":
          Error: Failed to get UPS data: No UPS data returned from apcaccess
              at UPSService.getUPSData (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21359:19)
              at async UPSResolver.upsDevices (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21652:25)
    }
```

**Comment by ruaan-deysel** [comment]
> I cant really disable it i think, i can only stop it or am i missing something?
> 
> Otherwise below log keeps repeating (log is filled with it):
> 
> ```
> [23:01:24 ERROR UPSService]: Error getting UPS data: {"apiVersion":"4.29.2+c39b0b26","logger":"UPSService","context":"UPSService"}
> [23:01:24 ERROR ExceptionsHandler]: Failed to get UPS data: No UPS data returned from apcaccess {"apiVersion":"4.29.2+c39b0b26","logger":"ExceptionsHandler","context":"ExceptionsHandler"}
>     err: {
>       "type": "Error",
>       "message": "Failed to get UPS data: No UPS data returned from apcaccess",
>       "stack":
>           Error: Failed to get UPS data: No UPS data returned from apcaccess
>               at UPSService.getUPSData (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21359:19)
>               at async UPSResolver.upsDevices (file:///usr/local/unraid-api/dist/assets/plugin.module-Dsa5H7Ea.js:21652:25)
>     }
> ```

In Unraid --> Settings --> UPS Settings --> Start APC UPS Daemon. 

If I disable it, it generates the error in graphql log, when enabled it stops. 

The integration picks this up from GraphQL API. So I'm thinking the Unraid Dev team need to reduce the log level for "no UPS" scenarios (this is arguably a bug since it floods logs for users without UPS)

**Comment by ABEIDO** [comment]
Yeah i have set that to no so status is stopped (was just unsure there was a option to disable it over just stopped). But its only logging errors with integration to HA enabled, without integration no errors occur.

If i enabled it error goes away but the my NUT plugin goes haywire (Would only use APC deamon but have other dependencies that require NUT over default APC)

**Comment by PilaScat** [comment]
> > Hyphens, no spaces. I'll switch over to apcupsd and see if that helps at least the UPS part...
> 
> I checked and Unraid API doesn't support NUT yet and just the APCUPSD for now.

No need to add NUT, there is alredy his separate integration
Just disable polling UPS data if APCUPSD is disabled

**Comment by ABEIDO** [comment]
> > > Hyphens, no spaces. I'll switch over to apcupsd and see if that helps at least the UPS part...
> > 
> > 
> > I checked and Unraid API doesn't support NUT yet and just the APCUPSD for now.
> 
> No need to add NUT, there is alredy his separate integration Just disable polling UPS data if APCUPSD is disabled

By diabling ups data polling do you mean in code or is it something me as a user can edit as my grapapi log just keeps growing due to ups errors?

**Comment by PilaScat** [comment]
> By diabling ups data polling do you mean in code or is it something me as a user can edit as my grapapi log just keeps growing due to ups errors?

In the code, it was a suggestion for the dev
